Repository AY2223S2-CS2103T-W13-4/tp, pull requests merged in 2023-03, with the labels that each got.

#38 V1.2 (view lesson by subject, upcoming, done)
  src/main/java/seedu/address/logic/commands/CreateLessonCommand.java
  src/main/java/seedu/address/logic/commands/ViewLessonCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/CreateLessonCommandParser.java
  src/main/java/seedu/address/logic/parser/ViewLessonCommandParser.java
  src/main/java/seedu/address/model/student/LessonDonePredicate.java
  src/main/java/seedu/address/model/student/LessonSubjectPredicate.java
  src/main/java/seedu/address/model/student/Student.java
  src/main/java/seedu/address/model/student/UniqueLessonsList.java
  src/main/java/seedu/address/model/student/exceptions/DuplicateLessonException.java
  src/test/java/seedu/address/model/student/LessonBelongsToDatePredicateTest.java
  src/test/java/seedu/address/model/student/LessonDonePredicateTest.java
  src/test/java/seedu/address/model/student/LessonSubjectPredicateTest.java
  src/test/java/seedu/address/model/student/LessonTest.java
  src/test/java/seedu/address/model/student/UniqueLessonsListTest.java
Labels: type.Story, priority.Medium

#43 About us fahim
  docs/AboutUs.md
  docs/images/fahim-tazz.png
  docs/team/fahim-tazz.md
Labels: documentation

#50 Update command "add" to "new-student" and add Grade Level and School tags
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
Labels: priority.Medium

#53 bugfixes for view-exam
  src/main/java/seedu/address/logic/parser/ViewExamCommandParser.java
  src/main/java/seedu/address/logic/parser/ViewLessonCommandParser.java
  src/main/java/seedu/address/storage/JsonAdaptedStudent.java
Labels: type.Story

#44 Updating Developer guide
  docs/DeveloperGuide.md
  docs/index.md
Labels: documentation

#54 store exam locally, but sacrificed the throw exception functionality …
  src/main/java/seedu/address/logic/commands/CreateExamCommand.java
  src/main/java/seedu/address/model/student/Exam.java
  src/main/java/seedu/address/storage/JsonAdaptedStudent.java
Labels: type.Story, priority.High

#55 update view style for all view commands: now only students show has a…
  src/main/java/seedu/address/logic/commands/ViewExamCommand.java
  src/main/java/seedu/address/logic/commands/ViewHomeworkCommand.java
  src/main/java/seedu/address/logic/commands/ViewLessonCommand.java
Labels: type.Story, priority.Medium

#63 View bug fix and message update
  src/main/java/seedu/address/logic/commands/ViewExamCommand.java
  src/main/java/seedu/address/logic/commands/ViewHomeworkCommand.java
  src/main/java/seedu/address/logic/commands/ViewLessonCommand.java
  src/main/java/seedu/address/logic/parser/ViewExamCommandParser.java
  src/main/java/seedu/address/logic/parser/ViewHomeworkCommandParser.java
  src/main/java/seedu/address/logic/parser/ViewLessonCommandParser.java
Labels: type.Story, priority.High

#66 User guide v1.2
  docs/UserGuide.md
  docs/images/Ui.png
Labels: documentation

#70 updated message usage for create, view commands. updated command word…
  src/main/java/seedu/address/logic/commands/CreateExamCommand.java
  src/main/java/seedu/address/logic/commands/CreateLessonCommand.java
  src/main/java/seedu/address/logic/commands/ViewExamCommand.java
  src/main/java/seedu/address/logic/commands/ViewLessonCommand.java
  src/main/java/seedu/address/logic/commands/homework/CreateHomeworkCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
Labels: type.Story, priority.High

#72 Fix view homework bug
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/homework/ViewHomeworkCommand.java
  src/main/java/seedu/address/logic/parser/homework/ViewHomeworkCommandParser.java
  src/main/java/seedu/address/model/student/Student.java
  src/main/java/seedu/address/model/student/UniqueHomeworkList.java
  src/test/java/seedu/address/logic/parser/ViewHomeworkCommandParserTest.java
Labels: bug

#75 now name/ filter will result in an exception thrown if the name given…
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/CreateExamCommand.java
  src/main/java/seedu/address/logic/commands/CreateLessonCommand.java
  src/main/java/seedu/address/logic/commands/DeleteLessonCommand.java
  src/main/java/seedu/address/logic/commands/ViewExamCommand.java
  src/main/java/seedu/address/logic/commands/ViewLessonCommand.java
  src/main/java/seedu/address/logic/commands/homework/CreateHomeworkCommand.java
  src/main/java/seedu/address/logic/commands/homework/DeleteHomeworkCommand.java
  src/main/java/seedu/address/logic/commands/homework/MarkHomeworkAsDoneCommand.java
  src/main/java/seedu/address/logic/commands/homework/MarkHomeworkAsUndoCommand.java
  src/main/java/seedu/address/logic/commands/homework/UpdateHomeworkCommand.java
  src/main/java/seedu/address/logic/commands/homework/ViewHomeworkCommand.java
  src/main/java/seedu/address/logic/parser/CreateExamCommandParser.java
  src/main/java/seedu/address/logic/parser/CreateLessonCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteLessonCommandParser.java
  src/main/java/seedu/address/logic/parser/ViewExamCommandParser.java
  src/main/java/seedu/address/logic/parser/ViewLessonCommandParser.java
  src/main/java/seedu/address/logic/parser/homework/CreateHomeworkCommandParser.java
  src/main/java/seedu/address/logic/parser/homework/DeleteHomeworkCommandParser.java
  src/main/java/seedu/address/logic/parser/homework/MarkHomeworkAsDoneCommandParser.java
  src/main/java/seedu/address/logic/parser/homework/MarkHomeworkAsUndoCommandParser.java
  src/main/java/seedu/address/logic/parser/homework/UpdateHomeworkCommandParser.java
  src/main/java/seedu/address/logic/parser/homework/ViewHomeworkCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/student/NamePredicate.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/parser/ViewHomeworkCommandParserTest.java
Labels: type.Story, priority.High

#78 Fix UI bug
  src/main/java/seedu/address/ui/MainWindow.java
Labels: priority.High

#81 Update DG
  docs/AboutUs.md
  docs/DeveloperGuide.md
Labels: priority.High

#90 fix the bug where tags does not allow spaces to exist.
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/model/tag/Tag.java
Labels: type.Story, priority.High

#92 no message
  docs/DevOps.md
Labels: type.Story

#97 No such student found
  .gitignore
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/CreateExamCommand.java
  src/main/java/seedu/address/logic/commands/CreateLessonCommand.java
  src/main/java/seedu/address/logic/commands/DeleteExamCommand.java
  src/main/java/seedu/address/logic/commands/DeleteLessonCommand.java
  src/main/java/seedu/address/logic/commands/UpdateExamCommand.java
  src/main/java/seedu/address/logic/commands/UpdateLessonCommand.java
  src/main/java/seedu/address/logic/commands/ViewExamCommand.java
  src/main/java/seedu/address/logic/commands/ViewLessonCommand.java
  src/main/java/seedu/address/logic/commands/homework/CreateHomeworkCommand.java
  src/main/java/seedu/address/logic/commands/homework/DeleteHomeworkCommand.java
  src/main/java/seedu/address/logic/commands/homework/MarkHomeworkAsDoneCommand.java
  src/main/java/seedu/address/logic/commands/homework/MarkHomeworkAsUndoCommand.java
  src/main/java/seedu/address/logic/commands/homework/UpdateHomeworkCommand.java
  src/main/java/seedu/address/logic/commands/homework/ViewHomeworkCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: type.Story, priority.Medium

#100 Fix duplicate homework bug
  docs/index.md
  src/main/java/seedu/address/model/student/Student.java
Labels: bug, priority.High

#103 Update UG to include the new Assignment Command
  docs/UserGuide.md
  src/main/resources/view/MainWindow.fxml
Labels: priority.Medium

#101 Homework test cases
  src/test/java/seedu/address/logic/parser/homework/CreateHomeworkCommandParserTest.java
  src/test/java/seedu/address/logic/parser/homework/DeleteHomeworkCommandParserTest.java
  src/test/java/seedu/address/logic/parser/homework/MarkHomeworkAsDoneCommandParserTest.java
  src/test/java/seedu/address/logic/parser/homework/MarkHomeworkAsUndoCommandParserTest.java
  src/test/java/seedu/address/logic/parser/homework/UpdateHomeworkCommandParserTest.java
  src/test/java/seedu/address/logic/parser/homework/ViewHomeworkCommandParserTest.java
Labels: priority.Medium

#106 Fix date parsing bug
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/parser/ParserUtil.java
Labels: bug, priority.High

#110 Update User Guide with exam-related commands
  docs/UserGuide.md
Labels: documentation

#116 Update exam section
  docs/UserGuide.md
  docs/diagrams/UiFilledExamsContent.puml
  docs/images/UiFilledExamsContent.png
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/ui/exam/FilledExamsContent.java
  src/main/resources/view/ExamsContent.fxml
  src/test/java/seedu/address/logic/parser/CreateExamCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteExamCommandParserTest.java
  src/test/java/seedu/address/logic/parser/UpdateExamCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ViewExamCommandParserTest.java
Labels: priority.High

#123 Refactor homework
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/CommandUtil.java
  src/main/java/seedu/address/logic/commands/homework/CreateHomeworkCommand.java
  src/main/java/seedu/address/logic/commands/homework/DeleteHomeworkCommand.java
  src/main/java/seedu/address/logic/commands/homework/MarkHomeworkAsDoneCommand.java
  src/main/java/seedu/address/logic/commands/homework/MarkHomeworkAsUndoCommand.java
  src/main/java/seedu/address/logic/commands/homework/UpdateHomeworkCommand.java
  src/main/java/seedu/address/logic/commands/homework/ViewHomeworkCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/homework/CreateHomeworkCommandParser.java
  src/main/java/seedu/address/logic/parser/homework/DeleteHomeworkCommandParser.java
  src/main/java/seedu/address/logic/parser/homework/MarkHomeworkAsDoneCommandParser.java
  src/main/java/seedu/address/logic/parser/homework/MarkHomeworkAsUndoCommandParser.java
  src/main/java/seedu/address/logic/parser/homework/UpdateHomeworkCommandParser.java
  src/main/java/seedu/address/logic/parser/homework/ViewHomeworkCommandParser.java
Labels: priority.Medium

#124 Update user guide GUI Section
  docs/UserGuide.md
  docs/images/Exams.jpg
  docs/images/GUI.jpg
  docs/images/Homework.jpg
  docs/images/Lessons.jpg
  docs/images/Profile.jpg
  src/main/java/seedu/address/logic/commands/exceptions/CommandException.java
  src/main/java/seedu/address/ui/exam/FilledExamsContent.java
  src/main/resources/view/ProfileContent.fxml
  src/main/resources/view/stylesheet/DetailedInfoRegion.css
Labels: documentation, priority.High

#125 Fix view homework
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/homework/UpdateHomeworkCommand.java
  src/main/java/seedu/address/logic/commands/homework/ViewHomeworkCommand.java
Labels: bug, priority.High

#127 Exam Enhancements
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/exam/CreateExamCommand.java
  src/main/java/seedu/address/logic/commands/exam/UpdateExamCommand.java
  src/main/java/seedu/address/logic/commands/exam/ViewExamCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/exam/CreateExamCommandParser.java
  src/main/java/seedu/address/logic/parser/exam/UpdateExamCommandParser.java
  src/main/java/seedu/address/model/student/Exam.java
  src/main/java/seedu/address/model/student/Grade.java
  src/main/java/seedu/address/model/student/Student.java
  src/main/java/seedu/address/model/student/UniqueExamList.java
  src/test/java/seedu/address/model/student/ExamTest.java
Labels: enhancement
