Repository AY2223S2-CS2103T-W13-4/tp, pull requests merged in 2023-04, with the labels that each got.

#170 Yufan pe bug
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/homework/UpdateHomeworkCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/exam/CreateExamCommandParser.java
  src/main/java/seedu/address/ui/exam/ExamCard.java
  src/main/java/seedu/address/ui/lesson/LessonCard.java
Labels: bug

#173 Boqian ped bugs
  docs/UserGuide.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/lesson/CreateLessonCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
Labels: bug, type.Story

#174 Lesson exam list index
  docs/UserGuide.md
  docs/images/delete-homework.jpg
  docs/images/mark-homework.jpg
  docs/images/new-homework.jpg
  docs/images/unmark-homework.jpg
  docs/images/update-homework.jpg
  docs/images/view-homework.jpg
  src/main/java/seedu/address/ui/exam/ExamCard.java
  src/main/java/seedu/address/ui/lesson/LessonCard.java
  src/main/resources/view/ExamListCard.fxml
  src/main/resources/view/LessonListCard.fxml
Labels: bug

#181 fix ped bug where commands consider names in a case-sensitive manner.
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/student/NamePredicate.java
Labels: bug, type.Story, priority.High

#180 Lwe conflict bug
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/lesson/CreateLessonCommand.java
  src/main/java/seedu/address/logic/commands/lesson/UpdateLessonCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/student/Exam.java
  src/main/java/seedu/address/model/student/Student.java
  src/main/java/seedu/address/model/student/UniqueExamList.java
  src/main/java/seedu/address/model/student/UniqueLessonsList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: bug, type.Story, priority.High

#184 now done/ can only be followed by either "done" or "not done". UG for…
  docs/UserGuide.md
  docs/images/delete-lesson.jpg
  docs/images/new-lesson.jpg
  docs/images/update-lesson.jpg
  docs/images/view-lesson.jpg
  src/main/java/seedu/address/logic/commands/exam/ViewExamCommand.java
  src/main/java/seedu/address/logic/commands/lesson/ViewLessonCommand.java
  src/main/java/seedu/address/logic/parser/exam/ViewExamCommandParser.java
  src/main/java/seedu/address/logic/parser/lesson/ViewLessonCommandParser.java
Labels: type.Story

#185 Update Yufan ppp
  docs/UserGuide.md
  docs/team/yufannnn.md
Labels: documentation

#189 fix the bug for lesson and exam where update does not throw error whe…
  docs/team/nbqian.md
  src/main/java/seedu/address/logic/commands/exam/UpdateExamCommand.java
  src/main/java/seedu/address/logic/commands/lesson/UpdateLessonCommand.java
Labels: bug, type.Story, priority.High

#190 Ped fix update command
  src/main/java/seedu/address/logic/commands/EditCommand.java
Labels: priority.High

#192 now if the user tries to add an exam to a student that clashes with t…
  src/main/java/seedu/address/logic/commands/exam/CreateExamCommand.java
  src/main/java/seedu/address/model/student/Student.java
  src/main/java/seedu/address/model/student/exceptions/ConflictingExamsException.java
Labels: type.Story

#193 Great Update of UG
  docs/UserGuide.md
  docs/team/yufannnn.md
  src/main/java/seedu/address/model/student/Homework.java
Labels: documentation, priority.High

#194 exam features changes to UG
  docs/UserGuide.md
Labels: documentation

#195 Update Create Homework Related Section
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/exam/CreateExamCommand.java
  src/main/java/seedu/address/logic/commands/homework/CreateHomeworkCommand.java
  src/main/java/seedu/address/logic/commands/lesson/CreateLessonCommand.java
  src/main/java/seedu/address/logic/parser/homework/CreateHomeworkCommandParser.java
Labels: bug, documentation

#198 create Glossary section of DG. Update TOC for DG
  docs/DeveloperGuide.md
Labels: type.Story

#197 Update PPP
  docs/DeveloperGuide.md
  docs/diagrams/ClickButtonActivityDiagram.puml
  docs/diagrams/ExamsClickSequenceDiagram.puml
  docs/diagrams/HomeworkClickSequenceDiagram.puml
  docs/diagrams/LessonsClickSequenceDiagram.puml
  docs/diagrams/ProfileClickSequenceDiagram.puml
  docs/diagrams/UiDetailedInfoSectionDiagram.puml
  docs/diagrams/UiProfileContent.puml
  docs/diagrams/UiQuickAccessButton.puml
  docs/images/ClickButtonActivityDiagram.png
  docs/images/ExamsClickSequenceDiagram.png
  docs/images/HomeworkClickSequenceDiagram.png
  docs/images/LessonsClickSequenceDiagram.png
  docs/images/ProfileClickSequenceDiagram.png
  docs/images/UiDetailedInfoSectionDiagram.png
  docs/images/UiFilledExamsContent.png
  docs/images/UiFilledHomeworkContent.png
  docs/images/UiFilledLessonsContent.png
  docs/images/UiProfileContent.png
  docs/images/UiQuickAccessButton.png
  docs/team/yufannnn.md
Labels: documentation

#199 Fix storage bug
  docs/UserGuide.md
  src/main/java/seedu/address/model/student/UniqueHomeworkList.java
  src/main/java/seedu/address/storage/JsonAdaptedHomework.java
  src/main/java/seedu/address/storage/JsonAdaptedTag.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/ui/command/CommandBox.java
  src/main/java/seedu/address/ui/command/ResultDisplay.java
  src/main/java/seedu/address/ui/detail/DetailedContent.java
  src/main/java/seedu/address/ui/detail/DetailedInfoRegion.java
  src/main/java/seedu/address/ui/detail/HeaderBar.java
  src/main/java/seedu/address/ui/detail/ProfileContent.java
  src/main/java/seedu/address/ui/exam/FilledExamsContent.java
Labels: bug, priority.High

#200 fix the bug where editing a student's info results in all his homewor…
  docs/team/nbqian.md
  src/main/java/seedu/address/logic/commands/EditCommand.java
Labels: bug, type.Story, priority.High

#203 Fix dg bug
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation

#206 Fix dg bug
  docs/diagrams/UiQuickAccessButton.png
  docs/diagrams/UiQuickAccessButton.puml
  docs/images/UiQuickAccessButton.png
  src/main/java/seedu/address/model/student/Exam.java
  src/main/java/seedu/address/model/student/Student.java
  src/main/java/seedu/address/model/student/UniqueExamList.java
  src/main/java/seedu/address/model/student/UniqueHomeworkList.java
  src/main/java/seedu/address/ui/homework/FilledHomeworkContent.java
Labels: bug

#207 Finalize UG for submission.
  docs/UserGuide.md
  docs/images/Ui.png
Labels: documentation

#212 Fix dg bug
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddCommand.java
Labels: bug

#237 v1.4b
  src/main/java/seedu/address/logic/commands/exam/ViewExamCommand.java
Labels: v1.4b
